version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5000:5000
    env_file: ./.env
    environment:
      DEBUG: 1
    depends_on:
    - postgres
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test
    ports:
      - 5432:5432