from pydantic import BaseModel, Field
from bson import ObjectId

from app.schemas.seats import Seat
from app.schemas.events import Event
from app.tools import PyObjectId


class Room(BaseModel):
    """
        :param seats: all places that generated by number of column and rows
        :param name: Name of room if it has
        :param columns: count of columns in the room
        :param rows: count of rows in the room
    """
    name: str | None = None
    seats: list[Seat] | None = None
    events: list[Event] | None = None

    class Config:
        orm_mode = True
